---
title: "Untitled"
output: github_document
---

```{r}
install.packages("rentrez")
install.packages("RCurl")
install.packages(c('devtools','curl'))
install.packages('rvest')
library(rentrez)
library(RCurl)
library(c('devtools','curl'))
library(rvest)

#The NCBI makes data available through a web interface, an FTP server and through a REST API called the Entrez Utilities, this package should allow us to access it.  Some other jazz changed since Adam taught this last so I had to install and load the other packages you see as well.
```



```{r}

n=50 #Set number of search results wanted
vivax_search <- entrez_search(db = "pubmed",
                              term = "Biostatistics[MeSH Major Topic", retmax=n) #Altered to view biostats

multi_summs <- entrez_summary(db="pubmed", id=vivax_search$ids, retmax=n)


date_and_cite <- extract_from_esummary(multi_summs,"uid") ##CAN GET CITATIONS

keywords<-c()
keywordCounter=1

for(i in 1:n){

##CANNONT DIRECTLY GET KEY WORDS

url<-paste("https://www.ncbi.nlm.nih.gov/pubmed/",date_and_cite[i], sep="" )

#This body of code grabs the keylist
results <- read_html(url)
papers <- html_nodes(results, ".rprt")
keys_html <- html_nodes(papers, ".keywords")
keys <- html_text(keys_html)



if(length(keys)==0){#If no keywords do nothing
}else{#Split of string make a list of characters
keylist.0 <- unlist(strsplit(keys, ": ",fixed=TRUE))
keylist<- unlist(strsplit(keylist.0[2], "; "))

for(a in 1:length(keylist)){
  keywords[keywordCounter] <- keylist[a]
  keywordCounter <- keywordCounter+1
}
}
}

print(keywords)
```

```{r}
#Test
pubmed

pubmed <- array(character(),c(2,4,0))
pubmed[,1]<-1

PlaceKeeper=1
  
pubmed[1,PlaceKeeper] <- date_and_cite[PlaceKeeper] #For Title

PlaceKeeper<-PlaceKeeper+1

pubmed[1][PlaceKeeper] <- date_and_cite[PlaceKeeper] #For pmcrefcount

PlaceKeeper<-3

author.df<-date_and_cite[[3]]
authorlist<-as.vector(author.df[,1])
pubmed[1][PlaceKeeper] <- authorlist #For authors

PlaceKeeper<-PlaceKeeper+1
    
##CANNONT DIRECTLY GET KEY WORDS

url<-paste("https://www.ncbi.nlm.nih.gov/pubmed/",date_and_cite[PlaceKeeper], sep="" )

results <- read_html(url)
papers <- html_nodes(results, ".rprt")


keys_html <- html_nodes(papers, ".keywords")
keys <- html_text(keys_html)
if(is.null(dim(keys))){
pubmed[1][PlaceKeeper] <- NA  
}else{
keylist.0 <- unlist(strsplit(keys, ": ",fixed=TRUE))
keylist<- unlist(strsplit(keylist.0[2], "; "))
pubmed[1][PlaceKeeper] <- keylist}

```
